### ISSUE TITLE
Boolean and integer values are not serialized correctly.

### ISSUE THREAD

**Issue by GillesTourreau** [PosInformatique/PosInformatique.MSBuild.Yaml#6]
When using the following YAML:
```yaml
object:
   boolValue: true
   integerValue: 1234
```

The following JSON content is generated and the boolean and integer values are considered as string:
```json
{
  "object": {
    "boolValue": "true",
    "integerValue": "1234"
  }
}
```
